### ISSUE TITLE
Press y when a car pops up instead of a

### ISSUE THREAD

**Issue by OdeuoOreo** [ErikDuba/FH5-Sniping-Script#1]
Hey can you make it so it is pressing y and then selects buy car. This is faster than pressing a and then buying  out.

**Comment by ErikDuba** [comment]
Hi! Thanks for the suggestion. I uploaded the new .exe so try it out!

**Comment by Enrique-Groeneveld** [comment]
Thanks for submitting an issue, where quite new with this whole python thing!
